# Generated by Django 5.2.12 on 2026-05-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'routes_usertrip',
            },
        ),
        migrations.CreateModel(
            name='UserTripConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('duration_in_travel', models.IntegerField()),
                ('duration_waiting', models.IntegerField()),
                ('duration_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_connections', to='logistics.stop')),
                ('gtfs_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.trip')),
                ('starting_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_connections', to='logistics.stop')),
                ('user_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='trips.usertrip')),
            ],
            options={
                'db_table': 'routes_usertripconnection',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
    ]
