# Generated by Django 5.2.12 on 2026-03-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('city_lat', models.FloatField(blank=True, null=True)),
                ('city_long', models.FloatField(blank=True, null=True)),
                ('city_feature_class', models.CharField(blank=True, max_length=10, null=True)),
                ('city_feature_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('city_cc2', models.CharField(blank=True, max_length=60, null=True)),
                ('city_admin1_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city_admin2_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city_admin3_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city_admin4_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city_population', models.BigIntegerField(blank=True, null=True)),
                ('city_timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_code', models.CharField(blank=True, max_length=5, null=True)),
                ('stop_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('stop_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(max_length=8)),
                ('departure_time', models.CharField(max_length=8)),
                ('stop_sequence', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['stop', 'departure_time'], name='routes_stop_stop_id_20fe7e_idx'), models.Index(fields=['trip', 'stop_sequence'], name='routes_stop_trip_id_ebc0b3_idx')],
            },
        ),
    ]
