# Generated by Django 5.2.12 on 2026-03-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('attraction_name', models.CharField(max_length=255)),
                ('attraction_category', models.CharField(blank=True, max_length=100, null=True)),
                ('attraction_lat', models.FloatField()),
                ('attraction_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StopAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.IntegerField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.attraction')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.stop')),
            ],
            options={
                'unique_together': {('stop', 'attraction')},
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='stops',
            field=models.ManyToManyField(related_name='attractions', through='routes.StopAttraction', to='routes.stop'),
        ),
    ]
