# Generated by Django 5.2.12 on 2026-03-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_attraction_stopattraction_attraction_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_admin1_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_admin2_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_admin3_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_admin4_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_cc2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_feature_class',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_feature_code',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='city_country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_region_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('place_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('place_importance', models.FloatField(blank=True, null=True)),
                ('place_type', models.CharField(blank=True, max_length=255, null=True)),
                ('place_rank', models.IntegerField(blank=True, null=True)),
                ('place_suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('place_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.city')),
            ],
        ),
        migrations.AddField(
            model_name='stop',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.place'),
        ),
    ]
