# Generated by Django 5.2.12 on 2026-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_usertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
