# Generated by Django 5.2.12 on 2026-05-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_usertrip_end_date_alter_usertrip_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTripConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('duration_in_travel', models.IntegerField()),
                ('duration_waiting', models.IntegerField()),
                ('duration_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_connections', to='routes.stop')),
                ('gtfs_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.trip')),
                ('starting_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_connections', to='routes.stop')),
                ('user_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='routes.usertrip')),
            ],
            options={
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
    ]
