# Generated by Django 5.2.12 on 2026-05-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('attraction_name', models.CharField(max_length=255)),
                ('attraction_category', models.CharField(blank=True, max_length=100, null=True)),
                ('attraction_lat', models.FloatField()),
                ('attraction_lon', models.FloatField()),
            ],
            options={
                'db_table': 'routes_attraction',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'routes_calendar',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('city_lat', models.FloatField(blank=True, null=True)),
                ('city_long', models.FloatField(blank=True, null=True)),
                ('city_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('city_country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_population', models.BigIntegerField(blank=True, null=True)),
                ('city_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('city_thumbnail_url', models.URLField(blank=True, null=True)),
                ('city_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes_city',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'routes_route',
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.calendar')),
            ],
            options={
                'db_table': 'routes_calendardate',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('place_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('place_importance', models.FloatField(blank=True, null=True)),
                ('place_type', models.CharField(blank=True, max_length=255, null=True)),
                ('place_rank', models.IntegerField(blank=True, null=True)),
                ('place_suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('place_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.city')),
            ],
            options={
                'db_table': 'routes_place',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_code', models.CharField(blank=True, max_length=5, null=True)),
                ('stop_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.place')),
            ],
            options={
                'db_table': 'routes_stop',
            },
        ),
        migrations.CreateModel(
            name='StopAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.IntegerField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.attraction')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.stop')),
            ],
            options={
                'db_table': 'routes_stopattraction',
                'unique_together': {('stop', 'attraction')},
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='stops',
            field=models.ManyToManyField(related_name='attractions', through='logistics.StopAttraction', to='logistics.stop'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.route')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.calendar')),
            ],
            options={
                'db_table': 'routes_trip',
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('stop_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(max_length=8)),
                ('departure_time', models.CharField(max_length=8)),
                ('stop_sequence', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.trip')),
            ],
            options={
                'db_table': 'routes_stoptime',
                'indexes': [models.Index(fields=['stop', 'departure_time'], name='routes_stop_stop_id_20fe7e_idx'), models.Index(fields=['trip', 'stop_sequence'], name='routes_stop_trip_id_ebc0b3_idx')],
            },
        ),
    ]
